MODEL:
  DATA_DIM: 100
  SEQ_LEN: 20
  IC_ENC_DIM: 100
  CI_ENC_DIM: 100
  CON_DIM: 100
  CO_DIM: 4
  IC_DIM: 100
  GEN_DIM: 100
  FAC_DIM: 30
  DROPOUT_RATE: 0.05
  CD_RATE: 0.25
  CD_PASS_RATE: 0.0
  CO_PRIOR_TAU: 10.0
  CO_PRIOR_NVAR: 0.1
  IC_PRIOR_VAR: 0.1
  IC_POST_VAR_MIN: 1.0e-4
TRAIN:
  DATA:
    DIR: /snel/share/runs/nomad/Jango_data_chopped_4_nocorr
    PREFIX: lfads
  PATIENCE: 150
  BATCH_SIZE: 128
  MAX_EPOCHS: 10000
  MAX_GRAD_NORM: 200.0
  LOSS_SCALE: 1.0
  LR: 
    INIT: 0.001
    STOP: 1.0e-10
    DECAY: 1.0
    PATIENCE: 6
  L2:
    START_EPOCH: 0
    INCREASE_EPOCH: 100
    IC_ENC_SCALE: 0.0
    CI_ENC_SCALE: 0.0
    GEN_SCALE: 6.00e-4
    CON_SCALE: 7.25e-4
  KL:
    START_EPOCH: 0
    INCREASE_EPOCH: 100
    IC_WEIGHT: 1.60e-3
    CO_WEIGHT:  3.05e-5
  TUNE_MODE: True
  USE_TB: False
  MODEL_DIR: '' # specified once an experiment id has been assigned
  OVERWRITE: True
